// Code generated by metricsgen. DO NOT EDIT.

package blocksync

import (
	"github.com/go-kit/kit/metrics/discard"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	stdprometheus "github.com/prometheus/client_golang/prometheus"
)

func PrometheusMetrics(namespace string, labelsAndValues ...string) *Metrics {
	labels := []string{}
	for i := 0; i < len(labelsAndValues); i += 2 {
		labels = append(labels, labelsAndValues[i])
	}
	return &Metrics{
		Syncing: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "syncing",
			Help:      "Whether or not a node is block syncing. 1 if yes, 0 if no.",
		}, labels).With(labelsAndValues...),
		NumTxs: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "num_txs",
			Help:      "Number of transactions in the latest block.",
		}, labels).With(labelsAndValues...),
		TotalTxs: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "total_txs",
			Help:      "Total number of transactions.",
		}, labels).With(labelsAndValues...),
		BlockSizeBytes: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "block_size_bytes",
			Help:      "Size of the latest block.",
		}, labels).With(labelsAndValues...),
		LatestBlockHeight: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "latest_block_height",
			Help:      "The height of the latest block.",
		}, labels).With(labelsAndValues...),
		PeerBlockRequestsDropped: prometheus.NewCounterFrom(stdprometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "peer_block_requests_dropped",
			Help:      "Total number of BlockRequest messages dropped for exceeding a peer's block-sync request rate limit.",
		}, labels).With(labelsAndValues...),
		PeerLimiterWindows: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "peer_limiter_windows",
			Help:      "Current number of peer identities with a tracked block-sync request window. Sampled post-sweep, so this reflects steady-state map size rather than a transient peak.",
		}, labels).With(labelsAndValues...),
		PeerLimiterBans: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "peer_limiter_bans",
			Help:      "Current number of peer identities banned for exceeding their block-sync request window. Sampled post-sweep.",
		}, labels).With(labelsAndValues...),
		SubnetBlockRequestsDropped: prometheus.NewCounterFrom(stdprometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "subnet_block_requests_dropped",
			Help:      "Total number of BlockRequest messages dropped for exceeding a remote subnet's (see ipRateLimitKey) block-sync request rate limit.",
		}, labels).With(labelsAndValues...),
		SubnetLimiterWindows: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "subnet_limiter_windows",
			Help:      "Current number of remote subnets with a tracked block-sync request window. Sampled post-sweep.",
		}, labels).With(labelsAndValues...),
		SubnetLimiterBans: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "subnet_limiter_bans",
			Help:      "Current number of remote subnets banned for exceeding their block-sync request window. Sampled post-sweep.",
		}, labels).With(labelsAndValues...),
		PersistentPeerRequestsExempted: prometheus.NewCounterFrom(stdprometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "persistent_peer_requests_exempted",
			Help:      "Total number of BlockRequest messages served to a persistent peer (see IsPersistent) without either rate limiter applied.",
		}, labels).With(labelsAndValues...),
		BlockBytesServed: prometheus.NewCounterFrom(stdprometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "block_bytes_served",
			Help:      "Total bytes of BlockResponse handed to the transport, counting the block, its extended commit and envelope overhead.",
		}, labels).With(labelsAndValues...),
		ServingBudgetDrops: prometheus.NewCounterFrom(stdprometheus.CounterOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "serving_budget_drops",
			Help:      "Total number of BlockRequest messages dropped because the node-wide serving budget, a remote subnet's share of it, or a remote address's rolling byte quota was exhausted.",
		}, labels).With(labelsAndValues...),
		ServingBudgetTokens: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "serving_budget_tokens",
			Help:      "Bytes currently available in the node-wide serving budget. Sampled post-sweep. Negative while the budget is repaying an under-estimated response.",
		}, labels).With(labelsAndValues...),
		ServingSubnetBudgets: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "serving_subnet_budgets",
			Help:      "Current number of remote subnets with a tracked serving-budget share. Sampled post-sweep.",
		}, labels).With(labelsAndValues...),
		ServingPeerQuotas: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "serving_peer_quotas",
			Help:      "Current number of remote addresses with a tracked byte quota. Sampled post-sweep.",
		}, labels).With(labelsAndValues...),
	}
}

func NopMetrics() *Metrics {
	return &Metrics{
		Syncing:                        discard.NewGauge(),
		NumTxs:                         discard.NewGauge(),
		TotalTxs:                       discard.NewGauge(),
		BlockSizeBytes:                 discard.NewGauge(),
		LatestBlockHeight:              discard.NewGauge(),
		PeerBlockRequestsDropped:       discard.NewCounter(),
		PeerLimiterWindows:             discard.NewGauge(),
		PeerLimiterBans:                discard.NewGauge(),
		SubnetBlockRequestsDropped:     discard.NewCounter(),
		SubnetLimiterWindows:           discard.NewGauge(),
		SubnetLimiterBans:              discard.NewGauge(),
		PersistentPeerRequestsExempted: discard.NewCounter(),
		BlockBytesServed:               discard.NewCounter(),
		ServingBudgetDrops:             discard.NewCounter(),
		ServingBudgetTokens:            discard.NewGauge(),
		ServingSubnetBudgets:           discard.NewGauge(),
		ServingPeerQuotas:              discard.NewGauge(),
	}
}
